apiVersion: 1

providers:
  - name: Boat Operations
    orgId: 1
    folder: Boat Operations
    folderUid: cfw7cxz4cit4we
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/boat-dashboards
      foldersFromFilesStructure: false
